<?php
echo '<!doctype html>';
echo '<html class="no-js" lang="en">';
echo '';
echo '<head>';
echo '<meta charset="utf-8">';
echo '';
echo '<title>Chirag mental health chatbot</title>';
echo '';
echo '<meta name="description" content="">';
echo '<meta name="viewport" content="width=device-width, initial-scale=1">';
echo '';
echo '<link rel="shortcut icon" href="assets/images/favicon.png" type="image/png">';
echo '';
echo '<link rel="stylesheet" href="assets/css/animate.css">';
echo '';
echo '<link rel="stylesheet" href="assets/css/magnific-popup.css">';
echo '';
echo '<link rel="stylesheet" href="assets/css/slick.css">';
echo '';
echo '<link rel="stylesheet" href="assets/css/LineIcons.css">';
echo '';
echo '<link rel="stylesheet" href="assets/css/font-awesome.min.css">';
echo '';
echo '<link rel="stylesheet" href="assets/css/bootstrap.min.css">';
echo '';
echo '<link rel="stylesheet" href="assets/css/default.css">';
echo '';
echo '<link rel="stylesheet" href="assets/css/style.css">';
echo '';
echo '</head>';
echo '';
echo '<body>';
echo '<div class="preloader">';
echo '<div class="loader">';
echo '<div class="ytp-spinner">';
echo '<div class="ytp-spinner-container">';
echo '<div class="ytp-spinner-rotator">';
echo '<div class="ytp-spinner-left">';
echo '<div class="ytp-spinner-circle"></div>';
echo '</div>';
echo '<div class="ytp-spinner-right">';
echo '<div class="ytp-spinner-circle"></div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<header class="header-area">';
echo '<div class="navbar-area">';
echo '<div class="container">';
echo '<div class="row">';
echo '<div class="col-lg-12">';
echo '<nav class="navbar navbar-expand-lg">';
echo '<a class="navbar-brand" href="index.html">';
echo '<img src="assets/images/favicon.png" alt="Logo" width="50px" style="border-radius: 30px;">';
echo '</a>';
echo '<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">';
echo '<span class="toggler-icon"></span>';
echo '<span class="toggler-icon"></span>';
echo '<span class="toggler-icon"></span>';
echo '</button>';
echo '';
echo '<div class="collapse navbar-collapse sub-menu-bar" id="navbarSupportedContent">';
echo '<ul id="nav" class="navbar-nav ml-auto">';
echo '<li class="nav-item active">';
echo '<a class="page-scroll" href="#home">Home</a>';
echo '</li>';
echo '<li class="nav-item">';
echo '<a class="page-scroll" href="#features">Features</a>';
echo '</li>';
echo '<li class="nav-item">';
echo '<a class="page-scroll" href="#about">About</a>';
echo '</li>';
echo '<li class="nav-item">';
echo '<a class="page-scroll" href="#facts">Chatbot</a>';
echo '</li>';
echo '</ul>';
echo '</div>';
echo '</nav>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '<div id="home" class="header-hero bg_cover" style="background-image: url(assets/images/banner-bg.svg)">';
echo '<div class="container">';
echo '<div class="row justify-content-center">';
echo '<div class="col-lg-8">';
echo '<div class="header-hero-content text-center">';
echo '<h3 class="header-sub-title wow fadeInUp" data-wow-duration="1.3s" data-wow-delay="0.2s">Chirag</h3>';
echo '<h2 class="header-title wow fadeInUp" data-wow-duration="1.3s" data-wow-delay="0.5s">The Mental Health Chatbot</h2>';
echo '<p class="text wow fadeInUp" data-wow-duration="1.3s" data-wow-delay="0.8s">Feel stressed or depressed?<br>Try Chirag and get Impressed!</p>';
echo '<a href="https://console.dialogflow.com/api-client/demo/embedded/fbab4d24-ba07-4d9b-a945-4e5fa82d63ae" class="main-btn wow fadeInUp" data-wow-duration="1.3s" data-wow-delay="1.1s">Get Started</a>';
echo '</div> <!-- header hero content -->';
echo '</div>';
echo '</div> <!-- row -->';
echo '<div class="row">';
echo '<div class="col-lg-12">';
echo '<div class="header-hero-image text-center wow fadeIn" data-wow-duration="1.3s" data-wow-delay="1.4s">';
echo '<img src="assets/images/header-hero.png" alt="hero" style="border-radius: 30px;">';
echo '</div> <!-- header hero image -->';
echo '</div>';
echo '</div> <!-- row -->';
echo '</div> <!-- container -->';
echo '<div id="particles-1" class="particles"></div>';
echo '</div> <!-- header hero -->';
echo '</header>';
echo '<section id="features" class="services-area pt-120">';
echo '<div class="container">';
echo '<div class="row justify-content-center">';
echo '<div class="col-lg-10">';
echo '<div class="section-title text-center pb-40">';
echo '<div class="line m-auto"></div>';
echo '<h3 class="title">There is something in you, <span> that the world needs</span></h3>';
echo '</div> <!-- section title -->';
echo '</div>';
echo '</div> <!-- row -->';
echo '<div class="row justify-content-center">';
echo '<div class="col-lg-4 col-md-7 col-sm-8">';
echo '<div class="single-services text-center mt-30 wow fadeIn" data-wow-duration="1s" data-wow-delay="0.2s">';
echo '<div class="services-icon">';
echo '<img class="shape" src="assets/images/services-shape.svg" alt="shape">';
echo '<img class="shape-1" src="assets/images/services-shape-1.svg" alt="shape">';
echo '<i class="lni-baloon"></i>';
echo '</div>';
echo '<div class="services-content mt-30">';
echo '<h4 class="services-title"><a href="#">Friendly</a></h4>';
echo '<p class="text">The chatbot has been feeded with friendly and motivating conversations. This makes the chatbot more as a friend than a application.</p>';
echo '</div>';
echo '</div> <!-- single services -->';
echo '</div>';
echo '<div class="col-lg-4 col-md-7 col-sm-8">';
echo '<div class="single-services text-center mt-30 wow fadeIn" data-wow-duration="1s" data-wow-delay="0.5s">';
echo '<div class="services-icon">';
echo '<img class="shape" src="assets/images/services-shape.svg" alt="shape">';
echo '<img class="shape-1" src="assets/images/services-shape-2.svg" alt="shape">';
echo '<i class="lni-cog"></i>';
echo '</div>';
echo '<div class="services-content mt-30">';
echo '<h4 class="services-title"><a href="#">Intelligent</a></h4>';
echo '<p class="text">The Google-Dialogflow chatbot is Intelligent enough to identify intents. Context has been added to the conversations for better user experience.</p>';
echo '</div>';
echo '</div> <!-- single services -->';
echo '</div>';
echo '<div class="col-lg-4 col-md-7 col-sm-8">';
echo '<div class="single-services text-center mt-30 wow fadeIn" data-wow-duration="1s" data-wow-delay="0.8s">';
echo '<div class="services-icon">';
echo '<img class="shape" src="assets/images/services-shape.svg" alt="shape">';
echo '<img class="shape-1" src="assets/images/services-shape-3.svg" alt="shape">';
echo '<i class="lni-bolt-alt"></i>';
echo '</div>';
echo '<div class="services-content mt-30">';
echo '<h4 class="services-title"><a href="#">Powerful</a></h4>';
echo '<p class="text">The Chatbot is made with Google-Dialogflow. This made it easier for the developers to feed in data and track the errors.</p>';
echo '</div>';
echo '</div> <!-- single services -->';
echo '</div>';
echo '</div> <!-- row -->';
echo '</div> <!-- container -->';
echo '</section>';
echo '<section id="about" class="about-area pt-70">';
echo '<div class="container">';
echo '<div class="row">';
echo '<div class="col-lg-6">';
echo '<div class="about-content mt-50 wow fadeInLeftBig" data-wow-duration="1s" data-wow-delay="0.5s">';
echo '<div class="section-title">';
echo '<div class="line"></div>';
echo '<h3 class="title">Open Source</h3>';
echo '</div> <!-- section title -->';
echo '<p class="text">You are not only a user, you are also a part of our team. Intrested users can contribute to our project on Github. This will assist us in better development of our project.';
echo '</p>';
echo '<a href="https://github.com/ABX9801/Chirag" class="main-btn">Contribute</a>';
echo '</div> <!-- about content -->';
echo '</div>';
echo '<div class="col-lg-6">';
echo '<div class="about-image text-center mt-50 wow fadeInRightBig" data-wow-duration="1s" data-wow-delay="0.5s">';
echo '<img src="assets/images/about1.svg" alt="about">';
echo '</div> <!-- about image -->';
echo '</div>';
echo '</div> <!-- row -->';
echo '</div> <!-- container -->';
echo '<div class="about-shape-1">';
echo '<img src="assets/images/about-shape-1.svg" alt="shape">';
echo '</div>';
echo '</section>';
echo '<section class="about-area pt-70">';
echo '<div class="about-shape-2">';
echo '<img src="assets/images/about-shape-2.svg" alt="shape">';
echo '</div>';
echo '<div class="container">';
echo '<div class="row">';
echo '<div class="col-lg-6 order-lg-last">';
echo '<div class="about-content mt-50 wow fadeInLeftBig" data-wow-duration="1s" data-wow-delay="0.5s">';
echo '<div class="section-title">';
echo '<div class="line"></div>';
echo '<h3 class="title">Mental Health <span> a Taboo in India</span></h3>';
echo '</div> <!-- section title -->';
echo '<p class="text">Mental Health is a critical issue in today’s health world. Mental Health is not something readily discussed in India. According to us the term Mental-Health in India is misunderstood as Mentally-Unstable. Depression is one of the most neglected problems in India. The only cure for depression and anxiousness is that we get to talk to people who can motivate us. Thus we have come up with an Idea of a Mental Health Chatbot that can be used for curing Depression and Anxiety</p>';
echo '</div> <!-- about content -->';
echo '</div>';
echo '<div class="col-lg-6 order-lg-first">';
echo '<div class="about-image text-center mt-50 wow fadeInRightBig" data-wow-duration="1s" data-wow-delay="0.5s">';
echo '<img src="assets/images/about2.svg" alt="about">';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</section>';
echo '<section class="about-area pt-70">';
echo '<div class="container">';
echo '<div class="row">';
echo '<div class="col-lg-6">';
echo '<div class="about-content mt-50 wow fadeInLeftBig" data-wow-duration="1s" data-wow-delay="0.5s">';
echo '<div class="section-title">';
echo '<div class="line"></div>';
echo '<h3 class="title"><span>Challenge : </span> Dataset for our chatbot.</h3>';
echo '</div>';
echo '<p class="text">Collecting the Dataset of the App is a great Challenge. There is no particular dataset available for the project. A lot of research got us some data of a few conversations.</p>';
echo '</div>';
echo '</div>';
echo '<div class="col-lg-6">';
echo '<div class="about-image text-center mt-50 wow fadeInRightBig" data-wow-duration="1s" data-wow-delay="0.5s">';
echo '<img src="assets/images/about3.svg" alt="about">';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="about-shape-1">';
echo '<img src="assets/images/about-shape-1.svg" alt="shape">';
echo '</div>';
echo '</section>';
echo '<section id="facts" class="video-counter pt-70">';
echo '<div class="container">';
echo '<div class="row">';
echo '<div class="col-lg-6">';
echo '<div class="video-content mt-50 wow fadeIn" data-wow-duration="1s" data-wow-delay="0.5s">';
echo '<center>';
echo '<div>';
echo '<iframe allow="microphone;" width="350" height="450" src="https://console.dialogflow.com/api-client/demo/embedded/fbab4d24-ba07-4d9b-a945-4e5fa82d63ae">';
echo '</iframe>';
echo '</div>';
echo '</center>';
echo '</div>';
echo '</div>';
echo '<div class="col-lg-6">';
echo '<div class="counter-wrapper mt-50 wow fadeIn" data-wow-duration="1s" data-wow-delay="0.8s">';
echo '<div class="counter-content">';
echo '<div class="section-title">';
echo '<div class="line"></div>';
echo '<h3 class="title">Enjoy the App</h3>';
echo '</div>';
echo '<p class="text">Speak out your feelings to Chirag and let him help you get out of your stressed life. Trust Chirag as he will not utter a single word to anyone. Chirag also cares for you and motivates you. Bee it a failure or social issues, Chirag has the solution for them all.</p>';
echo '</div>';
echo '<div class="row no-gutters">';
echo '<div class="col-4">';
echo '<div class="single-counter counter-color-1 d-flex align-items-center justify-content-center">';
echo '<div class="counter-items text-center">';
echo '<span class="count"><span class="counter">7</span></span>';
echo '<p class="text">Intents</p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="col-4">';
echo '<div class="single-counter counter-color-2 d-flex align-items-center justify-content-center">';
echo '<div class="counter-items text-center">';
echo '<span class="count"><span class="counter">5</span>K</span>';
echo '<p class="text">Lines of data</p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div> <!-- row -->';
echo '</div> <!-- container -->';
echo '</section>';
echo '<footer id="footer" class="footer-area pt-120">';
echo '<div class="container">';
echo '';
echo '<div class="footer-widget pb-100">';
echo '<div class="row">';
echo '<div class="col-lg-4 col-md-6 col-sm-8">';
echo '<div class="footer-about mt-50 wow fadeIn" data-wow-duration="1s" data-wow-delay="0.2s">';
echo '<a class="logo" href="#">';
echo '<img src="assets/images/favicon.png" alt="Logo" width="40px" style="border-radius: 100px;">';
echo '</a>';
echo '<p class="text">Made with by CCET</p>';
echo '</div> <!-- footer about -->';
echo '</div>';
echo '<div class="col-lg-5 col-md-7 col-sm-7">';
echo '<div class="footer-link d-flex mt-50 justify-content-md-between">';
echo '<div class="link-wrapper wow fadeIn" data-wow-duration="1s" data-wow-delay="0.4s">';
echo '</div> <!-- footer wrapper -->';
echo '</div> <!-- footer link -->';
echo '</div>';
echo '</div> <!-- row -->';
echo '</div> <!-- footer widget -->';
echo '</div> <!-- container -->';
echo '<div id="particles-2"></div>';
echo '</footer>';
echo '';
echo '<a href="#" class="back-to-top"><i class="lni-chevron-up"></i></a>';
echo '<!--====== Jquery js ======-->';
echo '<script src="assets/js/vendor/jquery-1.12.4.min.js"></script>';
echo '<script src="assets/js/vendor/modernizr-3.7.1.min.js"></script>';
echo '';
echo '<!--====== Bootstrap js ======-->';
echo '<script src="assets/js/popper.min.js"></script>';
echo '<script src="assets/js/bootstrap.min.js"></script>';
echo '';
echo '<!--====== Plugins js ======-->';
echo '<script src="assets/js/plugins.js"></script>';
echo '';
echo '<!--====== Slick js ======-->';
echo '<script src="assets/js/slick.min.js"></script>';
echo '';
echo '<!--====== Ajax Contact js ======-->';
echo '<script src="assets/js/ajax-contact.js"></script>';
echo '';
echo '<!--====== Counter Up js ======-->';
echo '<script src="assets/js/waypoints.min.js"></script>';
echo '<script src="assets/js/jquery.counterup.min.js"></script>';
echo '';
echo '<!--====== Magnific Popup js ======-->';
echo '<script src="assets/js/jquery.magnific-popup.min.js"></script>';
echo '';
echo '<!--====== Scrolling Nav js ======-->';
echo '<script src="assets/js/jquery.easing.min.js"></script>';
echo '<script src="assets/js/scrolling-nav.js"></script>';
echo '';
echo '<!--====== wow js ======-->';
echo '<script src="assets/js/wow.min.js"></script>';
echo '';
echo '<!--====== Particles js ======-->';
echo '<script src="assets/js/particles.min.js"></script>';
echo '';
echo '<!--====== Main js ======-->';
echo '<script src="assets/js/main.js"></script>';
echo '';
echo '</body>';
echo '';
echo '</html>';
echo '';
?>